### ISSUE TITLE
Allow only lock

### ISSUE THREAD

**Issue by bzumik1** [joerg65/tedee_lock#10]
Hi, I would like to ask if you plan to add feature which would allow to only lock the door. O would like to be sure that because of some bug my door will not be opened remotely.

I guess it would be easiest to handle this on token level (it would have right only to lock), but I haven't seen there this option.

**Comment by joerg65** [comment]
Is not enough, if you disable the open button in Tedee App? Or do you want it open from Tedee App, but block open function only in Homeassistant?

**Comment by bzumik1** [comment]
The second option, to be able to open in from tedee app and not from HA.

**Comment by joerg65** [comment]
Jakub, please jump to tedee_hass_integration of  Patrik Hilker. I do not maintain this here anymore.
