### ISSUE TITLE
Attributes not available

### ISSUE THREAD

**Issue by fprokop** [joerg65/tedee_lock#4]
After updating to the new lock.py the lock attributes are not available anymore
![2022-01-25_08h53_37](https://user-images.githubusercontent.com/75439345/150934674-ccba9fff-4e7d-4c98-b7df-e518e99d3680.png)

A rollback brings back the attributes, but also the device_state_attributes error message.

Core 2021.12.10 on HA OS virtual machine.

**Comment by joerg65** [comment]
Yes I know about. I have already a new version prepared. But it is also for a new version of pyTedee. For pyTedee I need to wait for a corrected pull request to make it ready to upload to PyPi.

**Comment by joerg65** [comment]
I made a small change that should bring back the attributes: https://github.com/joerg65/tedee_lock/commit/3383648dcfacf444ba2a17fea590d9def738b2a8
