### ISSUE TITLE
supported_features is hard-coded to 1

### ISSUE THREAD

**Issue by LordShadowen** [joerg65/tedee_lock#9]
First off, thanks for this integration - it's working really well.

The one issue I've found is that there seems to be some inconsistency with the "pullstring support"  state and the supported_features attribute.
In my case, the lock does not have pullstring enabled, and the attribute correctly reports that. However, in this section of the code, the supported_features is hard-coded to report the value 1:

```
    @property
    def supported_features(self):
        return SUPPORT_OPEN
```

Unless I misunderstood the documentation, the SUPPORT_OPEN means, opening the latch, which is the same thing... so this value is wrong (it should be 0 in my case, and not 1).

The impact of this is that some lovelace cards will show an "Open" button if they see that value as 1 - for example, the Mushroom Lock card does this (the button obviously does nothing, but it should not be there in the first place...)

**Comment by joerg65** [comment]
I know I do a late response...
In the code it is like that:
```
    @property
    def supported_features(self):
        """Flag supported features."""
        if parse_version('0.0.2') <= parse_version(pkg_resources.get_distribution('pytedee').version):
            if self._sensor.get_is_enabled_pullspring():
                return SUPPORT_OPEN
            else:
                return None
        else:
            return SUPPORT_OPEN

```

It seems you are referring to an old version.
